### ISSUE TITLE
Mixed language in messagebox

### ISSUE THREAD

**Issue by ts-korhonen** [laciba96/WinBox-Reloaded#2]
When deleting a VM there is mixed language in a message box. This is on the second release US-version.
![image](https://user-images.githubusercontent.com/80648513/118487727-ada5e180-b723-11eb-8c33-fdc869440dd4.png)

I think this has changed between the first and second release as I remember seeing the message fully in English before.

**Comment by laciba96** [comment]
Yeah, you're right it was good in the previous version. I fixed the translation, but I want to solve Issue #1, before I make a new release.
