### ISSUE TITLE
Splash screen is off-center

### ISSUE THREAD

**Issue by ts-korhonen** [laciba96/WinBox-Reloaded#6]
The splash screen is not on the center of main display. I have two displays and I think it's on the center of the combined resolution.

Example screenshot:
![image](https://user-images.githubusercontent.com/80648513/120083283-4d725080-c0d0-11eb-9d32-8e90f66d3dc8.png)
The main window is centered, splash screen is close to the right edge, that would continue to second display.

This is on the 1.0 final version.

**Comment by laciba96** [comment]
Thanks for the report, I also noticed this bug in multi-monitor setups.

It's a known issue, and it will be fixed in the next release. 
The commits, and the release itself will be available if my internal tests are done.

**Comment by laciba96** [comment]
This bug is theoretically solved in v1.1. Can you confirm it?

**Comment by ts-korhonen** [comment]
> This bug is theoretically solved in v1.1. Can you confirm it?

Yes. It is now in the center like the main window.
