### ISSUE TITLE
Emulator download/update language is wrong

### ISSUE THREAD

**Issue by ts-korhonen** [laciba96/WinBox-Reloaded#8]
There seems to be some translation error with the 1.1 version. This is what showed up briefly after start:
![image](https://user-images.githubusercontent.com/80648513/120336174-c35a0000-c2fa-11eb-9b7a-a130b61bd42d.png)

**Comment by laciba96** [comment]
It seems to me that the accents in the language key name makes the problem. I'll fix it soon.

**Comment by ts-korhonen** [comment]
Yes. v1.11 fixed it.
